<?php
/**
 * @file
 * Code for the Curso blog feature.
 */

include_once 'curso_blog.features.inc';

/**
 * Implements hook_block_view_alter().
 * Esto debería ir en otro módulo más adecuado
 * Aquí solo la lógica relacionada con la feature blog
 */
function curso_blog_block_view_alter(&$data, $block) {
  if ($block->module == 'search' && $block->delta == 'form') {
    $block->title = 'hola2';
  }

}

/**
 * Implements hook_menu()
 */
function curso_blog_menu() {
  $items['miruta'] = array(
    'title' => 'Primer ejemplo',
    'page callback' => '_curso_blog_miruta_basica',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  $items['miruta/%'] = array(
    'title' => 'Ejemplo con comodin',
    'page callback' => '_curso_blog_miruta_comodin',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  $items['usuarios/%curso_blog_usuario'] = array(
    'title' => 'Ejemplo con comodin',
    'page callback' => '_curso_blog_usuarios',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  return $items;
}

/**
 * Implements hook_menu_alter()
 */
function curso_blog_menu_alter(&$items) {
  $items['user/%']['page callback'] = '_curso_blog_hack';
  $items['user/%']['access callback'] = '_curso_blog_perm';
}

function _curso_blog_perm() {
  return TRUE;
}

function _curso_blog_miruta_basica() {
  return 'hola!';
}

function _curso_blog_miruta_comodin($name) {
  return 'Hola ' . $name . '!';
}

function curso_blog_usuario_load($uid) {
  $user = user_load($uid);
  return $user;
}

function _curso_blog_usuarios($user) {
  return 'Eres ' . $user->name;
}

function _curso_blog_hack($user) {
  return 'Hacked!';
}